### ISSUE TITLE
How should I classify my variation/port?

### ISSUE THREAD

**Issue by dansmindspace** [CodingTrain/Coding-Train-Logo#10]
I decided I would take the Logo design a 3D Challenge coin using OpenSCAD. Should I submit it as a Variation or a Port? If I submit it as a Port would it be alright to add images?

Front of the Coin
<img src="https://github.com/CodingTrain/Coding-Train-Logo/assets/50756864/f299e6ba-9d1b-43a9-8feb-fb04e68cd4f6" alt="Coin Front" width="300px">
Back of the Coin
<img src="https://github.com/CodingTrain/Coding-Train-Logo/assets/50756864/6169a949-3b19-49a2-98d1-e490f07f9de5" alt="Coin Front" width="300px">

//Fixed Image Sizes

**Comment by kfahn22** [comment]
This is so cool!!  Feel free to do either.  If you add as a variation, you can provide a link to a gist or your GitHub repo with the code.  If you upload a folder with your code,  we would love images!

**Comment by dansmindspace** [comment]
Thank you, will most likely submit as a variation as I feel it is more transformative than a direct port.
